import requests

from src.config import CRYPTLEX_BASE_URL


def authenticate(email, password, account_id):
    """Log in to Cryptlex and return an access token.

    Args:
        email: The user's Cryptlex email.
        password: The user's Cryptlex password.
        account_id: The user's Cryptlex account ID.

    Returns:
        str: A JWT access token.

    Raises:
        requests.HTTPError: If authentication fails.
    """
    resp = requests.post(
        f"{CRYPTLEX_BASE_URL}/accounts/login",
        json={
            "accountId": account_id,
            "email": email,
            "password": password,
        },
        headers={"Content-Type": "application/json"},
        timeout=15,
    )
    resp.raise_for_status()
    return resp.json()["accessToken"]


def create_license(access_token, product_id, **kwargs):
    """Create a new Cryptlex license.

    Args:
        access_token: JWT from authenticate().
        product_id: The Cryptlex product ID.
        **kwargs: License parameters forwarded to the Cryptlex API.

    Returns:
        dict: The created license object from Cryptlex.
    """
    body = {"productId": product_id}
    body.update(kwargs)

    resp = requests.post(
        f"{CRYPTLEX_BASE_URL}/licenses",
        json=body,
        headers={
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json",
        },
        timeout=15,
    )
    resp.raise_for_status()
    return resp.json()


def create_offline_activation(access_token, license_id, offline_request, response_validity):
    """Create an offline activation for a license.

    Args:
        access_token: JWT from authenticate().
        license_id: The Cryptlex license ID.
        offline_request: The encrypted offline activation request string
                         (generated by LexActivator on the client machine).
        response_validity: Duration in seconds for which the offline
                           response should remain valid.

    Returns:
        The offline activation response content from Cryptlex.
    """
    body = {
        "licenseId": license_id,
        "offlineRequest": offline_request,
        "responseValidity": response_validity,
    }

    resp = requests.post(
        f"{CRYPTLEX_BASE_URL}/activations/offline-activate",
        json=body,
        headers={
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json",
        },
        timeout=15,
    )
    resp.raise_for_status()
    return resp.text
